### ISSUE TITLE
Unlike inbounds, RPC._outbounds should actually be public

### ISSUE THREAD

**Issue by breerly** [yarpc/yarpc-python#56]
This allows runtime swapping of outbounds in programmatic settings, like with larry's phone procedure.

**Comment by abhinav** [comment]
Don't make the outbounds dict public and don't mutate it dynamically. For your purposes, once you have an outbound, you should be able to simply construct a client object with the outbound. Go and Java use a Channel object to contain the things needed for a client to function: the caller name, the service name, the outbound, and in the future, other channel-specific (or client-local) options.

Here's how I imagine that API could look for the dynamic outbounds case:

```python
client = json.client(Channel(caller='me', service='foo', outbound=outbound))
```

And in the normal use case it would be,

```python
client = json.client(rpc.channel('foo'))
```
